export const
	MARKET_CHANGE_FILTER = 'MARKET_CHANGE_FILTER',

	SEND_SEARCH_FRUITS = 'SEND_SEARCH_FRUITS',
	RECEIVE_SEARCH_FRUITS = 'RECEIVE_SEARCH_FRUITS',
	FAILED_SEARCH_FRUITS = 'FAILED_SEARCH_FRUITS';
